import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const z = require("zod/v4");
const bindingRefSchema = z.string().regex(/^binding_[0-9a-f-]{36}$/i).optional();
const cwdSchema = z.string().min(1).max(32_768).optional();

export function registerRepoTools(server, { authorityExecutor, continuityState = null }) {
  if (!authorityExecutor) return;

  server.registerTool(
    "codex.repo_search",
    {
      title: "Search Authorized Project",
      description: "Search text in an authorized project with ripgrep through official Codex command/exec. This is model-free: ChatGPT performs the reasoning and Codex App Server only executes the search under the resolved read-only permission profile.",
      inputSchema: z.object({
        query: z.string().min(1).max(8_192),
        cwd: cwdSchema,
        glob: z.string().min(1).max(4_096).optional(),
        maxResults: z.number().int().min(1).max(500).default(100),
        bindingRef: bindingRefSchema,
      }).strict(),
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    },
    async ({ query, cwd, glob, maxResults, bindingRef }) => structured(async () => {
      const scoped = bindingRef && continuityState ? continuityState.assertCwd(bindingRef, cwd) : null;
      const command = ["rg", "--line-number", "--column", "--no-heading", "--color", "never", "--max-count", String(maxResults)];
      if (glob) command.push("--glob", glob);
      command.push("--", query, ".");
      const result = await authorityExecutor.exec({ command, cwd: scoped?.targetCwd ?? cwd, access: "readOnly", timeoutMs: 15_000 });
      return projectCommandResult(result, { query, glob: glob ?? null });
    })
  );

  server.registerTool(
    "codex.git_status",
    {
      title: "Read Git Status",
      description: "Read git status for an authorized project via official Codex command/exec with read-only authority. Does not start a Codex model turn.",
      inputSchema: z.object({ cwd: cwdSchema, bindingRef: bindingRefSchema }).strict(),
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    },
    async ({ cwd, bindingRef }) => structured(async () => {
      const scoped = bindingRef && continuityState ? continuityState.assertCwd(bindingRef, cwd) : null;
      const result = await authorityExecutor.exec({ command: ["git", "status", "--short", "--branch"], cwd: scoped?.targetCwd ?? cwd, access: "readOnly", timeoutMs: 10_000 });
      return projectCommandResult(result);
    })
  );

  server.registerTool(
    "codex.git_diff",
    {
      title: "Read Git Diff",
      description: "Read the current git diff for an authorized project via official Codex command/exec with read-only authority. Can read staged or unstaged changes without starting a Codex model turn.",
      inputSchema: z.object({
        cwd: cwdSchema,
        staged: z.boolean().default(false),
        pathspec: z.array(z.string().min(1).max(4_096)).max(50).default([]),
        bindingRef: bindingRefSchema,
      }).strict(),
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    },
    async ({ cwd, staged, pathspec, bindingRef }) => structured(async () => {
      const scoped = bindingRef && continuityState ? continuityState.assertCwd(bindingRef, cwd) : null;
      const command = ["git", "diff"];
      if (staged) command.push("--cached");
      if (pathspec.length) command.push("--", ...pathspec);
      const result = await authorityExecutor.exec({ command, cwd: scoped?.targetCwd ?? cwd, access: "readOnly", timeoutMs: 15_000 });
      return projectCommandResult(result, { staged, pathspec });
    })
  );

  server.registerTool(
    "codex.apply_patch",
    {
      title: "Apply Authorized Project Patch",
      description: "Apply an OpenAI apply_patch patch generated by ChatGPT through official Codex command/exec. The patch is executed under the locally resolved Codex permission profile and does not start a Codex model turn. Use this for coherent multi-file edits; use precise_edit for guarded exact-text replacements.",
      inputSchema: z.object({
        patch: z.string().min(1).max(500_000),
        cwd: cwdSchema,
        bindingRef: bindingRefSchema,
      }).strict(),
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
    },
    async ({ patch, cwd, bindingRef }) => structured(async () => {
      if (!patch.startsWith("*** Begin Patch") || !patch.includes("*** End Patch")) throw new Error("apply_patch payload must use the *** Begin Patch / *** End Patch format");
      const scoped = bindingRef && continuityState ? continuityState.assertCwd(bindingRef, cwd) : null;
      const result = await authorityExecutor.exec({ command: ["apply_patch", patch], cwd: scoped?.targetCwd ?? cwd, access: "inherit", timeoutMs: 30_000 });
      if (bindingRef && continuityState) {
        continuityState.record(bindingRef, { kind: "patch", cwd: result.effectiveCwd, status: result.exitCode === 0 ? "applied" : "failed", exitCode: result.exitCode });
      }
      return projectCommandResult(result, { continuityJournaled: Boolean(bindingRef) });
    })
  );
}

function projectCommandResult(result, extra = {}) {
  return {
    status: result.exitCode === 0 ? "ok" : "failed",
    exitCode: result.exitCode,
    stdout: result.stdout,
    stderr: result.stderr,
    stdoutTruncated: result.stdoutTruncated === true,
    stderrTruncated: result.stderrTruncated === true,
    cwd: result.effectiveCwd ?? null,
    permissionProfile: result.permissionProfile ?? null,
    permissionCeiling: result.permissionCeiling ?? null,
    authoritySource: result.authoritySource ?? null,
    trustedAncestor: result.trustedAncestor ?? null,
    modelTurnStarted: false,
    ...extra,
  };
}

async function structured(task) {
  try {
    const payload = await task();
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload, isError: payload?.status === "failed" };
  } catch (error) {
    const payload = { error: error instanceof Error ? error.message : String(error) };
    if (typeof error?.code === "string") payload.errorCode = error.code;
    if (Array.isArray(error?.nextActions)) payload.nextActions = error.nextActions;
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload, isError: true };
  }
}
